### PR TITLE
Give all exported <dfn>s constant text.

### PR DESCRIPTION
**Pull request by jyasskin**
Including the promise variable in the definition text made it impossible
to use these terms verbatim in other specs.

### CODE REVIEW

**Comment by jyasskin** [comment]
@tabatkins, I marked "resolve", "reject", and "transforming" with `for=Promise` since they're relatively short terms, but if anyone ever introduces another use of those terms `for` something else, every spec is going to need to add a `link-defaults` for them.

Does it actually make sense to mark dfn-type definitions as "for" things?

**Comment by tabatkins** [comment]
You can provide a `data-lt` attribute giving one or more linking texts you want to use for the definitions; this is very useful with "phrase" type definitions, as you can give a few variants.

Marking dfn-type definitions with `for` definitely makes sense - it namespaces them.  It's probably not necessary for phrases like this, though.

**Comment by jyasskin** [comment]
'k, I'll remove the `for`s here then. I'll also go through and use all of these terms from within the document, to set a better example.

**Comment by annevk** [comment]
FWIW, I think specifications need to build on IDL (if they use IDL) or JavaScript directly when it comes to promises. The promises guide is a normative document.

**Comment by jyasskin** [comment]
Is it that "Findings" can't be normative? The promises guide abstract says specifically "It also includes a series of prose shorthands *you can use in your specification* to work with promises.", and it has a conformance section referring to "normative parts of this document". 

#27 tracks moving things into a better place, but until that's done, specs basically have to refer to this document in order to use promises conveniently.

**Comment by annevk** [comment]
Well, mostly, the layering would be wrong. It's ECMAScript -> IDL -> your spec. But yeah, it seems that's already being tracked and the relevant section will disappear.

**Comment by domenic** [comment]
Thank you very much, especially for updating all the other places in the spec!!

**Comment by domenic** [comment]
Merged as fb748a4aa46b5b82858067120fbdbef3d94ee731.

**Pull request closed without merging**
